artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Arsalan-Azhar-AI/datasets/raw/refs/heads/main/knowing-person-images-zip.zip
  #source_URL2: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  local_data_file2: /workspaces/End-to-End-Gender-Classification-project/celeba-dataset.zip
  unzip_dir: artifacts/data_ingestion

